version: '3'

services:
  hadoop-master:
    image: zhaolj/hadoop-arm:latest
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "50070:50070"  # Namenode UI
      - "8088:8088"    # Resource Manager UI
      - "19888:19888"  # Job History Server UI
    environment:
      - "SERVICE_PRECONDITION=namenode"
    volumes:
      - hadoop_data:/hadoop/dfs/name
    networks:
      - hadoop-network

  hadoop-worker1:
    image: zhaolj/hadoop-arm:latest
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    environment:
      - "SERVICE_PRECONDITION=dn"
    volumes:
      - hadoop_data:/hadoop/dfs/data
    networks:
      - hadoop-network

  hadoop-worker2:
    image: zhaolj/hadoop-arm:latest
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    environment:
      - "SERVICE_PRECONDITION=dn"
    volumes:
      - hadoop_data:/hadoop/dfs/data
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge

volumes:
  hadoop_data:
    driver: local

